#!/bin/env bash
# -------------------------------------------------------------------
#    a system info page generator from Linux Command Line
#
#   note:       
#   tested:     PASS
#   author:     merlinr@
# -------------------------------------------------------------------

# the formal and uncommon way to define immutable constant
declare -r TITLE="$HOSTNAME System Information Report"

CURRENT_TIME=$(date +"%x %r %Z")
TIME_STAMP="Generated $CURRENT_TIME by $USER"

report_uptime () {
    cat <<- EOF
        <h4>System Uptime</h4>
        <pre>$(uptime)</pre>
EOF
    return
}

report_disk_space () {
    cat <<- EOF
        <h4>Disk Space Utilization (in MB)</h4>
        <pre>$(df -h)</pre>
EOF
    return
}

report_home_space () {
    cat <<- EOF
        <h4>Home Space Utilization</h4>
        <pre>$(du -cmd1 ~ | sort -nr)</pre>
EOF
    return
}


cat << EOF
<html>
    <h2>
        <title><pre>$TITLE</pre></title>
    </h2>
    <body>
        <p>$TIME_STAMP</p>
        $(report_disk_space)
        $(report_uptime)
        $(report_home_space)
    </body>
</html>
EOF
